---
apiVersion: v1
data:
  LDAP_ADMIN_PASSWORD: cmVzdXBwbHktYXN0cm9uYXV0LWlvbg==
  LDAP_CONFIG_ADMIN_PASSWORD: cmVzdXBwbHktYXN0cm9uYXV0LWlvbg==
kind: Secret
metadata:
  name: ldap-user-creds
  namespace: openldap
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldap-service-cert
  namespace: openldap
spec:
  secretName: ldap-service-cert
  issuerRef:
    name: step-issuer
    kind: StepClusterIssuer
    group: certmanager.step.sm
  dnsNames:
    - ldap.ssigroup.io
    - ldap.k0.ssigroup.io
    - openldap.ldap.svc.cluster.local
